language: python
python:
  - "3.6.5"

#command to install dependencies

install:
 - pip install -r requirements.txt
 - pip install coveralls



#command to run tests
script:
  # - nose2 tests --with-coverage 
  - nosetests --with-coverage --cover-tests  --cover-package=tests
  - coverage report


after_success:
 - coveralls



